NeonMarket/Models/User.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NeonMarket.Models
{
    public class User : IdentityUser
    {
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}

NeonMarket/ViewModels/AuthenticationRelated/LoginCustomerVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NeonMarket.ViewModels.AuthenticationRelated
{
    public class LoginCustomerVM
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

NeonMarket/ViewModels/AuthenticationRelated/RegisterCustomerVM.cs
using NeonMarket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NeonMarket.ViewModels.AuthenticationRelated
{
    public class RegisterCustomerVM
    {
        public User User { get; set; }
        public string Password { get; set; }
    }
}

NeonMarket/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NeonMarket.Interfaces;
using NeonMarket.ViewModels.AuthenticationRelated;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NeonMarket.Controllers
{
    public class AuthenticationController : Controller
    {

        private IAuthenticationService authenticationService;
        private IHttpContextAccessor httpContextAccessor;

        public AuthenticationController(IAuthenticationService authenticationService, IHttpContextAccessor httpContextAccessor)
        {
            this.authenticationService = authenticationService;
            this.httpContextAccessor = httpContextAccessor;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginCustomerVM model)
        {
            return View();
        }


        public IActionResult RegisterCustomer() 
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RegisterCustomer(RegisterCustomerVM model)
        {

            ClaimsIdentity identity = authenticationService.GetClaimsIdentity(model.User);

            if (identity == null)
            {
                ModelState.AddModelError("", "Неправильный логин и (или) пароль");
                return View(model);
            }

            JwtSecurityToken jwtToken     = authenticationService.GetJWTToken(identity.Claims);
            string           access_token = authenticationService.GetAccessToken(jwtToken);

            IdentityResult userIdentity = await authenticationService.RegisteUserAsync(model);

            if (userIdentity == null)
            {

                ModelState.AddModelError("", "Внутренняя ошибка сервера");
                return View(model);
            }

            if (!userIdentity.Succeeded)
            {
                ModelState.AddModelError("", "Пользователь уже существует");
                return View(model);
            }


            // save into cookies
            httpContextAccessor.HttpContext.Response.Cookies.Append(".AspNetCore.Application.Id", access_token,
                new CookieOptions
                {
                 //   MaxAge = TimeSpan.FromMinutes(60)
                }
            );


            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = Constants.ROLE_ADMIN)]
        public IActionResult RegisterSupportModerator()
        {
            return View();
        }



        public IActionResult LoginREST()
        {
            return Ok();
        }

        public IActionResult RegisterCustomerREST(RegisterCustomerVM model)
        {
            return Ok();
        }
    }
}

NeonMarket/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NeonMarket.Models;

namespace NeonMarket.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

       
    }
}

NeonMarket/Views/Authentication/Login.cshtml
@model LoginCustomerVM

@{
    ViewData["Title"] = "Login";
}


<head>
    <meta charset="utf-8">
    <title>Логин</title>
    <link rel="stylesheet" href="~/css/Login.css">
</head>


<body>

    <div class="container">
        <div class="form">
            <h2>Авторизация</h2>
            <form>
                <div class="inputBox">
                    <input type="" placeholder="Е-мейл">
                </div>
                <div class="inputBox">
                    <input type="password" placeholder="Пароль">
                </div>
                <div class="inputBox">
                    <div class="neonbtn">
                        <input type="submit" value="Войти">
                        <input type="button" value="Регистрация" asp-action="Registration" asp-controller="Authentication" method="Get"> 
                    </div>
                </div>
                <p>Забыли пароль? <a href="#">Нажмите сюда</a></p>
            </form>
        </div>
    </div>


</body>

NeonMarket/Views/Authentication/RegisterCustomer.cshtml
@model RegisterCustomerVM

@{
    ViewData["Title"] = "Registation";
}

<head>
    <meta charset="utf-8">
    <title>Логин</title>
    <link rel="stylesheet" href="~/css/Registration.css">
</head>


<body>

    <div class="container">
        <div class="form">
            <h2>Регистрация</h2>
            <form asp-controller="Authentication" asp-action="RegisterCustomer">

                <div asp-validation-summary="ModelOnly"></div>

                <div class="inputBox">
                    <input type="text" placeholder="Имя" asp-for="User.Name">
                </div>

                <div class="inputBox">
                    <input type="text" placeholder="Фамилия" asp-for="User.Surname">
                </div>

                <div class="inputBox">
                    <input type="" placeholder="Е-мейл" asp-for="User.Email">
                </div>

                <div class="inputBox">
                    <input type="" placeholder="Номер телефона" asp-for="User.PhoneNumber">
                </div>

                <div class="inputBox">
                    <input type="password" placeholder="Пароль" asp-for="Password">
                </div>

                <div class="inputBox">
                    <div class="neonbtn">
                        <input type="submit" value="Зарегестрироваться">
                    </div>
                </div>

                <p>Есть аккаунт? <a href="#">Нажмите сюда</a></p>
            </form>
        </div>
    </div>


</body>

NeonMarket/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}



    <head>

        <link rel="stylesheet" href="~/css/MainPage.css">
        
    </head>






<body>

    <header>
        
        <div class="navigation">
            <div class="logo">
                <img src="~/img/logotype.png" alt="" class="logotype">
            </div>

            <div class="nav-menu">
                <ul class="menu">
                    <li class="nav-item"><a href="#" class="nav-link">Домой</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Доставка</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">О Нас</a></li>
                </ul>
            </div>

            <div class="search-block">
                <div class="searsh">
                    <input type="text" class="search-form" placeholder="Поиск">
                    <a href="#" class="search-btn"><i class="fas fa-search">Найти</i></a>
                </div>
            </div>

            <div class="personal-item">
                <div class="nav-menu2">
                    <ul class="menu2">
                        <li class="nav-item2"><a href="#" class="nav-link">Вход</a></li>
                        <li class="nav-item2"><a href="#" class="nav-link">Корзина</a></li>
                    </ul>
                </div>
                @*<div class="auth">
                    <div class="login">
                        <a href="#" class="auth-link"><i class="fas fa-user-circle"></i>Войти</a>
                    </div>
                    <div class="car">
                        <a href="#" class="auth-link"><i class="fas fa-shopping-cart"></i>Корзина</a>
                    </div>
                </div>*@
            </div>
        </div>

        <div class="main-information">
            <div class="text-inform">
                <h1>The new <strong>990</strong></h1>
                <p class="tagline">БЛА БЛА БЛА</p>
                <div class="inform-link">
                    <div class="inform-btn read">Читать далее</div>
                    <div class="inform-btn shop">Купить сейчас</div>
                </div>
            </div>

            <div class="photo-model">
                <img src="~/img/model.png" alt="">
            </div>
        </div>

        <div class="social">
            <div class="find">
                <a href="#"><i class="fas fa-map-marker-alt"></i>Найти магазин</a>
            </div>

            <div class="social-menu">
               

                <ul class="social-icon">
                    <li><a href="#" class="social-link"><i class="fab fa-facebook"></i></a></li>
                    <li><a href="#" class="social-link"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="#" class="social-link"><i class="fab fa-pinterest"></i></a></li>
                    <li><a href="#" class="social-link"><i class="fab fa-youtube"></i></a></li>
                    <li><a href="#" class="social-link"><i class="fab fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
      

    </header>




    @*<div class="text-center">
            <p> <a asp-action="Login" asp-controller="Authentication">Вход</a></p>
            <p> <a asp-action="RegisterCustomer" asp-controller="Authentication">Регистрация</a></p>

            @if (User.Identity.IsAuthenticated)
            {
                <p>Юзер авторизированый</p>
            }

        </div>*@


</body>

NeonMarket/Views/Shared/Registration.cshtml
@{
    ViewData["Title"] = "Registation";
}

<head>
    <meta charset="utf-8">
    <title>Логин</title>
    <link rel="stylesheet" href="~/css/Registration.css">
</head>


<body>

    <div class="container">
        <div class="form">
            <h2>Регистрация</h2>
            <form>
                <div class="inputBox">
                    <input type="text" placeholder="Имя">
                </div>
                <div class="inputBox">
                    <input type="text" placeholder="Фамилия">
                </div>
                <div class="inputBox">
                    <input type="" placeholder="Е-мейл">
                </div>
                <div class="inputBox">
                    <input type="" placeholder="Номер телефона">
                </div>
                <div class="inputBox">
                    <input type="password" placeholder="Пароль">
                </div>
                <div class="inputBox">
                    <input type="submit" value="Зарегестрироваться">
                </div>
                <p>Есть аккаунт? <a href="#">Нажмите сюда</a></p>
            </form>
        </div>
    </div>


</body>

NeonMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NeonMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Header.css">


</head>
<body>


    
</body>



</html>